dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
install: "${PWD}/target/travis-settings/java/install.sh"
script: "${PWD}/target/travis-settings/java/script.sh"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
env:
  global:
    secure: ZK4G+JWrUtkEVi59kP8tXihtU/qDEjsnCp3fapUh8YKvs5Ie0UjXRG3qIT7Wt9xEelB6ajbu0Nwi4fzt8XUT3YUT+tUJLjFe1lngUMyqj6Vpk7dpYcI7Hyvs5tJynS6v2B7+Vtg35lv7UbEhVRPCUD2xbU6CNGGDXtN29FIWNsbVfSVgISQzn270XoZ8ZEH1p2vqTCRe5eD2DaNrgPD+SYfmt438IeU3HwUNfhh7OTvenqbobtJetxUDnxh+W5Aj8A0FsaHSj6VUTFzt0REeFwI9etsk3vbrvIVCDI92mrh0jNpQmZfJgwfiCTS5yG0ZgNOZTCNEprO8CDFDpreDgfk+r/pB2M8fLByt1PnEN/25t5D6XE0MHX1DNDTtsVK7JNChtDUcWHNUK1p3PyoT13u+gkM+NL1gQuTdysTkO561bRn2P6UxxtFsyYddw3A2oQAKZ+GEvkNglf0IJo3jglNhwnvbcdEe/okStHABXCEOSWyLDILpZfNJYXI6+MvVNkUigXl1ZQHaISdWYr96ETK9VJ1dTz8h4QsOeqmGupyq3MP1RZhJx90x/0bJ5oHL9tHA/XtArgKqAm33C7NRvN/Cvr0gU/pt8SPAFbo3lGH9kwrjBhK/THvT7+WeFfe3c+c8NWj6v54+UhFXOuNoWUykNztDlNKpQGGz9989mQ8=
